# Generated by Django 4.2.17 on 2026-01-27 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email_announcements', models.BooleanField(default=True, help_text='Receive email notifications for course announcements')),
                ('email_grades', models.BooleanField(default=True, help_text='Receive email notifications when assignments are graded')),
                ('email_submissions', models.BooleanField(default=True, help_text='Receive email notifications for student submissions (instructors only)')),
                ('email_due_reminders', models.BooleanField(default=True, help_text='Receive email reminders before assignment due dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'accounts_userpreferences',
            },
        ),
    ]
