# Generated by Django 4.2.17 on 2026-07-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment', 'New Enrollment'), ('submission', 'New Submission'), ('grade', 'Assignment Graded'), ('new_lesson', 'New Lesson'), ('new_assignment', 'New Assignment'), ('resubmission', 'Resubmission Allowed'), ('announcement', 'New Announcement'), ('reply', 'New Reply')], max_length=20),
        ),
    ]
