# Generated by Django 4.2.17 on 2026-07-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_assignment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment', 'New Enrollment'), ('new_lesson', 'New Lesson'), ('announcement', 'New Announcement'), ('reply', 'New Reply'), ('badge_earned', 'Badge Earned')], max_length=20),
        ),
    ]
