# Generated by Django 4.2.17 on 2026-07-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='mastered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
