# Generated by Django 4.2.17 on 2026-01-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_announcement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False means student was removed (soft delete)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last time the student accessed the course', null=True),
        ),
    ]
