# Generated by Django 4.2.17 on 2026-01-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_enrollment_activity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_weight', models.DecimalField(decimal_places=2, default=50, help_text='Weight percentage for assignments (0-100)', max_digits=5)),
                ('quizzes_weight', models.DecimalField(decimal_places=2, default=50, help_text='Weight percentage for quizzes (0-100)', max_digits=5)),
                ('participation_weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight percentage for participation/lesson completion (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_config', to='courses.course')),
            ],
            options={
                'verbose_name': 'Grading Configuration',
                'db_table': 'courses_gradingconfig',
            },
        ),
    ]
