# Generated by Django 4.2.17 on 2026-01-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='current_section',
            field=models.PositiveIntegerField(default=0, help_text='Index of the current section the user is viewing'),
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional section title', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Section content in Markdown format')),
                ('video_type', models.CharField(blank=True, choices=[('none', 'No Video'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='none', max_length=20)),
                ('video_id', models.CharField(blank=True, help_text='YouTube or Vimeo video ID', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.lesson')),
            ],
            options={
                'db_table': 'courses_lessonsection',
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
