# Generated by Django 4.2.17 on 2026-01-29 21:22

from django.db import migrations


def create_initial_sections(apps, schema_editor):
    """
    Create an initial section for each existing lesson that has content or video.
    This ensures backward compatibility - existing lessons appear as single-section lessons.
    """
    Lesson = apps.get_model('courses', 'Lesson')
    LessonSection = apps.get_model('courses', 'LessonSection')

    for lesson in Lesson.objects.all():
        # Only create section if lesson has content or video
        if lesson.content or lesson.video_type != 'none':
            LessonSection.objects.create(
                lesson=lesson,
                title='',  # No title for auto-created sections
                content=lesson.content or '',
                video_type=lesson.video_type or 'none',
                video_id=lesson.video_id or '',
                order=0
            )


def reverse_initial_sections(apps, schema_editor):
    """
    Remove all sections with order=0 that have no title (auto-created).
    Restore content/video to lesson from section.
    """
    Lesson = apps.get_model('courses', 'Lesson')
    LessonSection = apps.get_model('courses', 'LessonSection')

    for lesson in Lesson.objects.all():
        section = LessonSection.objects.filter(lesson=lesson, order=0, title='').first()
        if section:
            # Restore content to lesson (in case it was modified)
            lesson.content = section.content
            lesson.video_type = section.video_type
            lesson.video_id = section.video_id
            lesson.save()
            section.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_sections'),
    ]

    operations = [
        migrations.RunPython(create_initial_sections, reverse_initial_sections),
    ]
