# Generated by Django 4.2.17 on 2026-07-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_two_weight_grading_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='score',
            field=models.PositiveIntegerField(help_text='Number of first-try correct answers'),
        ),
        migrations.CreateModel(
            name='LessonAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_answers', to='courses.lessonquizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_answers', to='courses.lessonquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_selections', to='courses.lessonquestionchoice')),
            ],
            options={
                'db_table': 'courses_lessonattemptanswer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
