# Generated by Django 4.2.30 on 2026-07-23 05:36

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_lessonquizattempt_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Stored lowercased', max_length=254)),
                ('token', models.CharField(default=courses.models.generate_invite_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=courses.models.default_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='courses.course')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_courseinvite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='courseinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('course', 'email'), name='unique_nonrevoked_invite_per_course_email'),
        ),
    ]
