# Generated by Django 4.2.30 on 2026-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_courseinvite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(choices=[('none', 'No Video'), ('youtube', 'YouTube')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='video_type',
            field=models.CharField(blank=True, choices=[('none', 'No Video'), ('youtube', 'YouTube')], default='none', max_length=20),
        ),
    ]
