# Generated by Django 5.2.16 on 2026-07-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_drop_dormant_lesson_quiz_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='layout',
            field=models.CharField(choices=[('doc', 'Document'), ('slide', 'Slide')], default='doc', help_text='How the player renders this page: scrolling document or slide stage', max_length=10),
        ),
    ]
