# Generated by Django 5.2.16 on 2026-07-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_lessonsection_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='image',
            field=models.ImageField(blank=True, db_default='', help_text='Slide image (set only by the slide-import endpoint)', upload_to='slide_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lessonsection',
            name='image_alt',
            field=models.TextField(blank=True, db_default='', help_text='Alt text for the slide image (extracted from the PDF text layer, editable)'),
        ),
    ]
