# Generated by Django 5.2.16 on 2026-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_lesson_content_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_locked',
            field=models.BooleanField(db_default=False, default=False, help_text='When true, students see the unit title and lesson count but cannot open its lessons or quizzes. Locked units drop out of every progress denominator. The instructor always sees full content.'),
        ),
    ]
