# Generated by Django 5.2.16 on 2026-08-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_unit_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_code',
            field=models.CharField(blank=True, help_text='Phase 67 invite fallback. A student who never received their invite email can redeem this code at /join — but only together with an email address that already has a pending CourseInvite on this course, so the code alone enrolls nobody. Null (the default for every course) means the fallback is off; Postgres permits many NULLs under a unique index.', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='courseinvite',
            name='email_error',
            field=models.CharField(blank=True, help_text='Truncated failure from the last send attempt, if it failed.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseinvite',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When our mail server accepted this invite for delivery.', null=True),
        ),
    ]
