# Generated by Django 4.2.17 on 2026-01-27 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_submissionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField()),
                ('grade_points', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_feedback', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assignments.submission')),
            ],
            options={
                'db_table': 'assignments_submissionhistory',
                'ordering': ['-archived_at'],
            },
        ),
    ]
