# Generated by Django 4.2.17 on 2026-01-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submissionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionhistory',
            name='files_info',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of file names from the archived submission'),
        ),
    ]
