# Generated by Django 4.2.17 on 2026-07-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='streak_freezes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Earned on level-up (max 2), auto-consumed on missed days'),
        ),
    ]
