# Generated by Django 4.2.17 on 2026-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_gameprofile_streak_freezes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_accessory',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_backdrop',
            field=models.CharField(default='plain', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_color',
            field=models.CharField(default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_eyes',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_headgear',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='mascot_name',
            field=models.CharField(default='Circuit', max_length=20),
        ),
    ]
