# Generated by Django 5.2.16 on 2026-07-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_gameprofile_avatar_accessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_aura',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_companion',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='avatar_held',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
